### ISSUE TITLE
Set up github

### ISSUE THREAD

**Issue by Rinary1** [ss14Starlight/space-station-14#52]
## Description

Set up issues, pr's, discussions, projects.

## TODO:
- [x] change issues template.
- [x] change PR's template.
- [ ] open Github Discussions for everyone.
- [x] add project plans.
